# # Everything need to be commented in secrets to avoid overwriting real secrets

# apiVersion: v1
# kind: Secret
# metadata:
#   name: srs-app-secrets
# type: Opaque
# stringData:
#   POSTGRES_PASSWORD: ""
#   LITELLM_API_KEY: ""
#   JWT_SECRET_KEY: ""
#   DASHBOARD_ADMIN_PASSWORD: ""
