services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    # ports:
    #   - "9092:9092"
    networks:
      - backend
    environment:
      CLUSTER_ID: 'MkU1qYWLT4yv1aB-b3G9NA'
      KAFKA_CLUSTER_ID: 'MkU1qYWLT4yv1aB-b3G9NA'
      KAFKA_NODE_ID: 1

      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT_INTERNAL'

      KAFKA_LOG_DIRS: '/var/lib/kafka/data'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:29092 --version || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    mem_limit: 2g

  kafka-topics-creator:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - common.env
      - .env
    command: >
      bash -c "
        export KAFKA_OPTS=\"-Dlog4j.configuration=file:/dev/null\" &&
        echo 'Waiting for Kafka to be ready...' &&
        cub kafka-ready -b kafka:29092 1 30 &&
        echo 'Kafka is ready!' &&
        kafka-topics --create --if-not-exists --topic $$KAFKA_RAW_TRANSACTIONS_TOPIC --bootstrap-server kafka:29092 --replication-factor 1 --partitions 4 &&
        kafka-topics --create --if-not-exists --topic $$KAFKA_VALIDATED_TRANSACTIONS_TOPIC --bootstrap-server kafka:29092 --replication-factor 1 --partitions 2 &&
        kafka-topics --create --if-not-exists --topic $$KAFKA_HUMAN_REVIEW_REQUIRED_TOPIC --bootstrap-server kafka:29092 --replication-factor 1 --partitions 1 &&
        kafka-topics --create --if-not-exists --topic $$KAFKA_FINAL_TRANSACTIONS_TOPIC --bootstrap-server kafka:29092 --replication-factor 1 --partitions 4 &&
        echo 'Topics created!'
      "

  # Databases
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    env_file:
      - common.env
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d transactions" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  # Application Services
  seeder:
    build:
      context: .
      dockerfile: docker/seeder.Dockerfile
    networks:
      - backend
    env_file:
      - common.env
      - .env
    depends_on:
      timescaledb:
        condition: service_healthy
    restart: on-failure

  generator:
    build:
      context: .
      dockerfile: docker/generator.Dockerfile
    networks:
      - backend
    env_file:
      - common.env
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      kafka-topics-creator:
        condition: service_completed_successfully
      seeder:
        condition: service_completed_successfully

  validator:
    build:
      context: .
      dockerfile: docker/validator.Dockerfile
    deploy:
      replicas: 2
    networks:
      - backend
    env_file:
      - common.env
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      kafka-topics-creator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      timescaledb:
        condition: service_healthy

  batch-ingestor:
    build:
      context: .
      dockerfile: docker/batch_ingestor.Dockerfile
    networks:
      - backend
    env_file:
      - common.env
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      kafka-topics-creator:
        condition: service_completed_successfully
      timescaledb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'src.batch_ingestor.main' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  reporter:
    build:
      context: .
      dockerfile: docker/reporter.Dockerfile
    ports:
      - "5005:5000"
    networks:
      - frontend
      - backend
    env_file:
      - common.env
      - .env
    depends_on:
      kafka-topics-creator:
        condition: service_completed_successfully
      timescaledb:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  kafka_data:
  postgres_data:
  redis_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge