
[project]
name = "transaction_fraud_detection_system"
version = "0.1.0"
dependencies = [
    "logging",
    "flask",
    "flask-sse",
    "redis[async]",
    "pyyaml",
    "jinja2",
    "aiokafka",
    "asyncpg",
    "sqlalchemy",
    "psycopg2-binary",
    "pydantic-settings"
]

[project.optional-dependencies]
dev = [
    "black",
    "ruff",
]
