apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator
  labels:
    app: validator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config/configmap.yaml") . | sha256sum }}
      labels:
        app: validator
    spec:
      containers:
        - name: validator
          image: "srs_validator:latest"
          imagePullPolicy: IfNotPresent # IfNotPresent | Never
          
          envFrom:
            - configMapRef:
                name: srs-environment-config
            - secretRef:
                name: srs-app-secrets

          # Good practice
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
