apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-validator-hpa 
  labels:
    app: validator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: validator 
  minReplicas: 2
  # maxReplicas: 
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
