apiVersion: v1
kind: Service
metadata:
  name: {{ include "transaction-fraud-detection.fullname" . }}
  labels:
    {{- include "transaction-fraud-detection.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "transaction-fraud-detection.selectorLabels" . | nindent 4 }}
