apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-anomaly-detection-monitor
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: anomaly-detection
  endpoints:
    - port: metrics
      interval: 2s