kafka:
  image:
    registry: docker.io
    repository: bitnamilegacy/kafka
    tag: "4.0.0-debian-12-r10"
  kraft:
    enabled: true
  zookeeper:
    enabled: false
  listeners:
    client:
      protocol: PLAINTEXT
  resources:
    limits:
      memory: 2Gi
  broker:
    offsetsTopicReplicationFactor: 1
    transactionStateLogReplicationFactor: 1
    transactionStateLogMinIsr: 1


redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
    # command: ["redis-server", "--appendonly", "yes"]


timescaledb-single:
  image:
    # registry: docker.io
    repository: timescale/timescaledb-ha
    tag: "pg15.17-ts2.27.0"
  fullnameOverride: "transaction-fraud-detection-timescaledb"
  secrets:
    credentials:
      PATRONI_SUPERUSER_PASSWORD: "password"
  persistentVolumes:
    data:
      size: 5Gi
