apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-fraud-triage-monitor
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: fraud-triage
  endpoints:
    - port: metrics
      interval: 2s