redis:
  host: redis
  port: 6379
  transaction_queue: "transaction_queue"
  correct_transactions_key: "correct_transactions"
  invalid_transactions_key: "invalid_transactions"
  invalid_transactions_list: "invalid_transactions_list"
  update_channel: "update_channel"
  generator_tps_key: "generator:target_tps"
  generator_invalid_perc_key: "generator:invalid_percentage"

# validator:
#   min_amount: 0
#   max_amount: 100000

generator:
  min_sleep_ms: 150
  max_sleep_ms: 2000
  default_tps: 2
  default_invalid_percentage: 10
