apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-reporter
  # name: reporter-service
  labels:
    app: reporter
spec:
  type: LoadBalancer 
  selector:
    app: reporter
  ports:
    - protocol: TCP
      port: 5005        # Browser port (localhost:5005)
      targetPort: 5005  # Internal port in kubernetes
    - name: metrics
      protocol: TCP
      port: 8005
      targetPort: 8005
