apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dashboard-api
  labels:
    app: dashboard-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-api
  template:
    metadata:
      labels:
        app: dashboard-api
    spec:
      containers:
        - name: dashboard-api
          image: "srs_dashboard_api:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: srs-environment-config
            - secretRef:
                name: srs-app-secrets