apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dashboard-api
  labels:
    app: dashboard-api
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: dashboard-api
